

services:
  app:
    container_name: quizzer_backend
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - quizzer-network
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  queue-worker:
    container_name: quizzer_queue
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - quizzer-network
    working_dir: /var/www
    command: php artisan queue:work

  nginx:
    container_name: quizzer_nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - quizzer-network
    depends_on:
      - app

networks:
  quizzer-network:

volumes:
  redis_data:

