<?php

return [
    'General Knowledge' => [
        'History',
        'Geography',
        'Science',
        'Literature',
        'World Politics',
        'Art & Culture',
        'Famous Landmarks',
        'Food & Drink',
        'Technology',
        'Human Body',
    ],
    'Pop Culture' => [
        'Music',
        'Movies',
        'TV Shows',
        'Celebrities',
        'Video Games',
        'Fashion',
        'Social Media Trends',
        'Comics & Graphic Novels',
        'Memes',
        'Famous Quotes',
    ],
    'Sports & Games' => [
        'Football (Soccer)',
        'Cricket',
        'Basketball',
        'Tennis',
        'Olympic Games',
        'Esports',
        'Board Games',
        'Poker & Casino Games',
        'Golf',
        'Formula 1',
    ],
    'Education & Academics' => [
        'Mathematics',
        'Physics',
        'Chemistry',
        'Biology',
        'Astronomy',
        'World Religions',
        'Philosophy',
        'Psychology',
        'Languages & Linguistics',
        'Economics',
    ],
    'Fun & Miscellaneous' => [
        'Animals',
        'Mythology',
        'Nature',
        'Inventions',
        'Cartoons',
        'Sci-Fi & Fantasy',
        'Superheroes & Villains',
        'Space Exploration',
        'World Records',
        'Riddles & Brain Teasers',
    ],
];
