<?php

namespace App\enums;


enum NotificationTitle: string
{
    case GIFT_CARD_AWARDED = 'GIFT_CARD_AWARDED';
    case GAME_INVITATION = 'GAME_INVITATION';
    case ZIVAS_UPDATED = 'ZIVAS_UPDATED';
    case FRIEND_REQUEST = 'FRIEND_REQUEST';
    case FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED';
    case FRIEND_REQUEST_REJECTED = 'FRIEND_REQUEST_REJECTED';
    case GAME_INVITATION_ACCEPTED = 'GAME_INVITATION_ACCEPTED';
    case GAME_INVITATION_REJECTED = 'GAME_INVITATION_REJECTED';
    case GAME_CANCELLED = 'GAME_CANCELLED';
    case GAME_ENDED = 'GAME_ENDED';
}